import { StyleSheet } from "react-native";
import theme from "./theme";

export const styles = StyleSheet.create({
  formContainer: {
    display: "flex",
    paddingTop: 15,
    paddingBottom: 15,
    backgroundColor: theme.colors.white,
    padding: 10,
  },
  submitButton: {
    backgroundColor: theme.colors.primary,
    color: theme.colors.white,
    padding: 10,
    borderRadius: 5,
    textAlign: "center",
  },
  separator: {
    height: 10,
  },
  container: {
    flex: 1,
    paddingTop: 10,
    paddingBottom: 10,
    backgroundColor: theme.colors.white,
    padding: 10,
    flexDirection: "row",
  },
  infoContainer: {
    flexDirection: "column",
    justifyContent: "space-around",
    paddingLeft: 5,
    paddingRight: 5,
    flex: 8,
  },
  ratingContainer: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    paddingRight: 5,
  },
  ratingBox: {
    width: 40,
    height: 40,
    justifyContent: "center",
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 2,
    borderColor: theme.colors.primary,
    borderRadius: 20,
  },
  openRepoButton: {
    flex: 1,
    backgroundColor: theme.colors.primary,
    color: theme.colors.white,
    padding: 10,
    borderRadius: 5,
    textAlign: "center",
    height: 40,
    display: "flex",
    alignItems: "center",
  },
  deleteRepoButton: {
    flex: 1,
    backgroundColor: theme.colors.appBarColor,
    color: theme.colors.white,
    padding: 10,
    borderRadius: 5,
    textAlign: "center",
    height: 40,
    display: "flex",
    alignItems: "center",
  },
});
